# Generated by Django 3.1.5 on 2021-01-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210119_0347'),
        ('departament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departament',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
            preserve_default=False,
        ),
    ]
