# Generated by Django 3.1.5 on 2021-01-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvertime_record', '0002_ouvertimerecord_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvertimerecord',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
