# Generated by Django 3.1.5 on 2021-02-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvertime_record', '0003_ouvertimerecord_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvertimerecord',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
