# Generated by Django 3.1.5 on 2021-01-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20210116_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='doc',
            field=models.FileField(default=1, upload_to='documents'),
            preserve_default=False,
        ),
    ]
