# Generated by Django 3.1.5 on 2021-01-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20210119_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cpf',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
