# Generated by Django 3.1.5 on 2021-01-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20210122_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default=1, upload_to='photo'),
            preserve_default=False,
        ),
    ]
